USE CobAuto;
GO

IF OBJECT_ID('dbo.CRM_USUARIO_ACCESO', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.CRM_USUARIO_ACCESO
    (
        ID INT IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_CRM_USUARIO_ACCESO PRIMARY KEY,

        USUARIO NVARCHAR(10) NOT NULL,

        PASSWORD_HASH VARCHAR(255) NULL,

        FLG_ACTIVO BIT NOT NULL
            CONSTRAINT DF_CRM_USUARIO_ACCESO_ACTIVO DEFAULT (1),

        FLG_CAMBIO_OBLIGATORIO BIT NOT NULL
            CONSTRAINT DF_CRM_USUARIO_ACCESO_CAMBIO DEFAULT (1),

        INTENTOS_FALLIDOS INT NOT NULL
            CONSTRAINT DF_CRM_USUARIO_ACCESO_INTENTOS DEFAULT (0),

        BLOQUEADO_HASTA DATETIME2(0) NULL,

        FECHA_CREACION DATETIME2(0) NOT NULL
            CONSTRAINT DF_CRM_USUARIO_ACCESO_CREACION DEFAULT (SYSDATETIME()),

        FECHA_CAMBIO_CLAVE DATETIME2(0) NULL,

        FECHA_ULTIMO_LOGIN DATETIME2(0) NULL,

        FECHA_ULTIMO_FALLO DATETIME2(0) NULL,

        USUARIO_CREACION NVARCHAR(10) NULL,

        USUARIO_ACTUALIZACION NVARCHAR(10) NULL,

        FECHA_ACTUALIZACION DATETIME2(0) NULL,

        CONSTRAINT UQ_CRM_USUARIO_ACCESO_USUARIO
            UNIQUE (USUARIO),

        CONSTRAINT CK_CRM_USUARIO_ACCESO_INTENTOS
            CHECK (INTENTOS_FALLIDOS >= 0)
    );

    CREATE INDEX IX_CRM_USUARIO_ACCESO_ACTIVO
        ON dbo.CRM_USUARIO_ACCESO (FLG_ACTIVO, USUARIO);
END;
GO
-------------------------------------------------------------------------

SELECT
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM CobAuto.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
  AND TABLE_NAME = 'CRM_USUARIO_ACCESO'
ORDER BY ORDINAL_POSITION;