#routes_score_telefonico.py
from fastapi import APIRouter, Query
from fastapi.responses import StreamingResponse
from app.services.score_telefonico_service import (
    buscar_score_telefonico,
    obtener_telefonos_cliente,
    obtener_catalogos_score,
    obtener_contexto_score,
    obtener_ultima_actualizacion_score,
    obtener_resumen_score,
    obtener_resultados_score,
    refrescar_score_telefonico,
    exportar_resultados_score
)

router = APIRouter()


@router.get("/contexto")
def contexto(
    usuario: str | None = Query(None),
    perfil: str | None = Query(None),
):
    return obtener_contexto_score(usuario=usuario, perfil=perfil)


@router.get("/ultima-actualizacion")
def ultima_actualizacion():
    return obtener_ultima_actualizacion_score()


@router.get("/resumen")
def resumen(
    idcartera: int = Query(...),
    condicion: str | None = Query(None),
    nuevo: str | None = Query(None),
    foco: str | None = Query(None),
    prioridad_banco: str | None = Query(None),
    producto: str | None = Query(None),
    rango_mora: str | None = Query(None),
    rango_capital: str | None = Query(None),
    rango_edad: str | None = Query(None),
    empresas_reportantes: str | None = Query(None),
    cuentas: str | None = Query(None),
    anio_cd_historico: str | None = Query(None),
    cluster_ml: str | None = Query(None),
    flag_top: str | None = Query(None),
    rango_campanas: str | None = Query(None),
    caseros: str | None = Query(None),
    estado_civil: str | None = Query(None),
    mg_contacto_cliente: str | None = Query(None),
    mg_indicador_cliente: str | None = Query(None),
    ug_contacto_cliente: str | None = Query(None),
    ug_indicador_cliente: str | None = Query(None),
    estado_pdp: str | None = Query(None),
    origen: str | None = Query(None),
    tipo_base: str | None = Query(None),
    prioridad_fono: str | None = Query(None),
    tipo_fono: str | None = Query(None),
    orden: str | None = Query(None),
    whatsapp: str | None = Query(None),
    osiptel: str | None = Query(None),
    timbrado: str | None = Query(None),
    intentos_equivocados: str | None = Query(None),
    apagados_ivr: str | None = Query(None),
    fallados_ivr: str | None = Query(None),
    zona: str | None = Query(None),
    marca_operativa: str | None = Query(None),
    timbrado_min: int | None = Query(None),
    intentos_equivocado_max: int | None = Query(None),
    apagado_ivr_max: int | None = Query(None),
    fallados_ivr_max: int | None = Query(None),
    search: str | None = Query(None),
):
    return obtener_resumen_score(
        idcartera=idcartera,
        condicion=condicion,
        nuevo=nuevo,
        foco=foco,
        prioridad_banco=prioridad_banco,
        producto=producto,
        rango_mora=rango_mora,
        rango_capital=rango_capital,
        rango_edad=rango_edad,
        empresas_reportantes=empresas_reportantes,
        cuentas=cuentas,
        anio_cd_historico=anio_cd_historico,
        cluster_ml=cluster_ml,
        flag_top=flag_top,
        rango_campanas=rango_campanas,
        caseros=caseros,
        estado_civil=estado_civil,
        mg_contacto_cliente=mg_contacto_cliente,
        mg_indicador_cliente=mg_indicador_cliente,
        ug_contacto_cliente=ug_contacto_cliente,
        ug_indicador_cliente=ug_indicador_cliente,
        estado_pdp=estado_pdp,
        origen=origen,
        tipo_base=tipo_base,
        prioridad_fono=prioridad_fono,
        tipo_fono=tipo_fono,
        orden=orden,
        whatsapp=whatsapp,
        osiptel=osiptel,
        timbrado=timbrado,
        intentos_equivocados=intentos_equivocados,
        apagados_ivr=apagados_ivr,
        fallados_ivr=fallados_ivr,
        zona=zona,
        marca_operativa=marca_operativa,
        timbrado_min=timbrado_min,
        intentos_equivocado_max=intentos_equivocado_max,
        apagado_ivr_max=apagado_ivr_max,
        fallados_ivr_max=fallados_ivr_max,
        search=search,
    )


@router.get("/resultados")
def resultados(
    idcartera: int = Query(...),
    page: int = Query(1),
    page_size: int = Query(25),
    search: str | None = Query(None),
    order_by: str | None = Query("SCORE_FINAL"),
    order_dir: str | None = Query("DESC"),
    condicion: str | None = Query(None),
    nuevo: str | None = Query(None),
    foco: str | None = Query(None),
    prioridad_banco: str | None = Query(None),
    producto: str | None = Query(None),
    rango_mora: str | None = Query(None),
    rango_capital: str | None = Query(None),
    rango_edad: str | None = Query(None),
    empresas_reportantes: str | None = Query(None),
    cuentas: str | None = Query(None),
    anio_cd_historico: str | None = Query(None),
    cluster_ml: str | None = Query(None),
    flag_top: str | None = Query(None),
    rango_campanas: str | None = Query(None),
    caseros: str | None = Query(None),
    estado_civil: str | None = Query(None),
    mg_contacto_cliente: str | None = Query(None),
    mg_indicador_cliente: str | None = Query(None),
    ug_contacto_cliente: str | None = Query(None),
    ug_indicador_cliente: str | None = Query(None),
    estado_pdp: str | None = Query(None),
    origen: str | None = Query(None),
    tipo_base: str | None = Query(None),
    prioridad_fono: str | None = Query(None),
    tipo_fono: str | None = Query(None),
    orden: str | None = Query(None),
    whatsapp: str | None = Query(None),
    osiptel: str | None = Query(None),
    timbrado: str | None = Query(None),
    intentos_equivocados: str | None = Query(None),
    apagados_ivr: str | None = Query(None),
    fallados_ivr: str | None = Query(None),
    zona: str | None = Query(None),
    marca_operativa: str | None = Query(None),
    timbrado_min: int | None = Query(None),
    intentos_equivocado_max: int | None = Query(None),
    apagado_ivr_max: int | None = Query(None),
    fallados_ivr_max: int | None = Query(None),
):
    return obtener_resultados_score(
        idcartera=idcartera,
        page=page,
        page_size=page_size,
        search=search,
        order_by=order_by,
        order_dir=order_dir,
        condicion=condicion,
        nuevo=nuevo,
        foco=foco,
        prioridad_banco=prioridad_banco,
        producto=producto,
        rango_mora=rango_mora,
        rango_capital=rango_capital,
        rango_edad=rango_edad,
        empresas_reportantes=empresas_reportantes,
        cuentas=cuentas,
        anio_cd_historico=anio_cd_historico,
        cluster_ml=cluster_ml,
        flag_top=flag_top,
        rango_campanas=rango_campanas,
        caseros=caseros,
        estado_civil=estado_civil,
        mg_contacto_cliente=mg_contacto_cliente,
        mg_indicador_cliente=mg_indicador_cliente,
        ug_contacto_cliente=ug_contacto_cliente,
        ug_indicador_cliente=ug_indicador_cliente,
        estado_pdp=estado_pdp,
        origen=origen,
        tipo_base=tipo_base,
        prioridad_fono=prioridad_fono,
        tipo_fono=tipo_fono,
        orden=orden,
        whatsapp=whatsapp,
        osiptel=osiptel,
        timbrado=timbrado,
        intentos_equivocados=intentos_equivocados,
        apagados_ivr=apagados_ivr,
        fallados_ivr=fallados_ivr,
        zona=zona,
        marca_operativa=marca_operativa,
        timbrado_min=timbrado_min,
        intentos_equivocado_max=intentos_equivocado_max,
        apagado_ivr_max=apagado_ivr_max,
        fallados_ivr_max=fallados_ivr_max,
    )


@router.get("/buscar")
def buscar(
    cartera: str | None = Query(None),
    dni: str | None = Query(None),
    telefono: str | None = Query(None),
    busqueda: str | None = Query(None),
    condicion: str | None = Query(None),
    condicion_excluir: str | None = Query(None),
    foco: str | None = Query(None),
    foco_excluir: str | None = Query(None),
    prioridad_banco: str | None = Query(None),
    prioridad_banco_excluir: str | None = Query(None),
    prioridad_contacto: str | None = Query(None),
    prioridad_fono: str | None = Query(None),
    prioridad_fono_excluir: str | None = Query(None),
    whatsapp: str | None = Query(None),
    whatsapp_excluir: str | None = Query(None),
    osiptel: str | None = Query(None),
    osiptel_excluir: str | None = Query(None),
    timbrado_min: int | None = Query(None),
    origen: str | None = Query(None),
    origen_excluir: str | None = Query(None),
    tipo_base: str | None = Query(None),
    tipo_base_excluir: str | None = Query(None),
    producto: str | None = Query(None),
    producto_excluir: str | None = Query(None),
    rango_mora: str | None = Query(None),
    rango_mora_excluir: str | None = Query(None),
    rango_capital: str | None = Query(None),
    rango_capital_excluir: str | None = Query(None),
    rango_edad: str | None = Query(None),
    rango_edad_excluir: str | None = Query(None),
    estado_civil: str | None = Query(None),
    estado_civil_excluir: str | None = Query(None),
    empresas_reportantes: str | None = Query(None),
    empresas_reportantes_excluir: str | None = Query(None),
    mg_contacto_cliente: str | None = Query(None),
    mg_contacto_cliente_excluir: str | None = Query(None),
    mg_indicador_cliente: str | None = Query(None),
    mg_indicador_cliente_excluir: str | None = Query(None),
    ug_contacto_cliente: str | None = Query(None),
    ug_contacto_cliente_excluir: str | None = Query(None),
    ug_indicador_cliente: str | None = Query(None),
    ug_indicador_cliente_excluir: str | None = Query(None),
    estado_pdp: str | None = Query(None),
    estado_pdp_excluir: str | None = Query(None),
    fecha_compromiso: str | None = Query(None),
    tipo_fono: str | None = Query(None),
    tipo_fono_excluir: str | None = Query(None),
    orden: str | None = Query(None),
    orden_excluir: str | None = Query(None),
    intentos_equivocado_max: int | None = Query(None),
    apagado_ivr_max: int | None = Query(None),
    fallados_ivr_max: int | None = Query(None),
    marca_operativa: str | None = Query(None),
    zona: str | None = Query(None),
    score_min: int | None = Query(None),
    page: int = Query(1),
    limit: int = Query(50)
):
    return buscar_score_telefonico(
        cartera=cartera,
        dni=dni,
        telefono=telefono,
        busqueda=busqueda,
        condicion=condicion,
        condicion_excluir=condicion_excluir,
        foco=foco,
        foco_excluir=foco_excluir,
        prioridad_banco=prioridad_banco,
        prioridad_banco_excluir=prioridad_banco_excluir,
        prioridad_contacto=prioridad_contacto,
        prioridad_fono=prioridad_fono,
        prioridad_fono_excluir=prioridad_fono_excluir,
        whatsapp=whatsapp,
        whatsapp_excluir=whatsapp_excluir,
        osiptel=osiptel,
        osiptel_excluir=osiptel_excluir,
        timbrado_min=timbrado_min,
        origen=origen,
        origen_excluir=origen_excluir,
        tipo_base=tipo_base,
        tipo_base_excluir=tipo_base_excluir,
        producto=producto,
        producto_excluir=producto_excluir,
        rango_mora=rango_mora,
        rango_mora_excluir=rango_mora_excluir,
        rango_capital=rango_capital,
        rango_capital_excluir=rango_capital_excluir,
        rango_edad=rango_edad,
        rango_edad_excluir=rango_edad_excluir,
        estado_civil=estado_civil,
        estado_civil_excluir=estado_civil_excluir,
        empresas_reportantes=empresas_reportantes,
        empresas_reportantes_excluir=empresas_reportantes_excluir,
        mg_contacto_cliente=mg_contacto_cliente,
        mg_contacto_cliente_excluir=mg_contacto_cliente_excluir,
        mg_indicador_cliente=mg_indicador_cliente,
        mg_indicador_cliente_excluir=mg_indicador_cliente_excluir,
        ug_contacto_cliente=ug_contacto_cliente,
        ug_contacto_cliente_excluir=ug_contacto_cliente_excluir,
        ug_indicador_cliente=ug_indicador_cliente,
        ug_indicador_cliente_excluir=ug_indicador_cliente_excluir,
        estado_pdp=estado_pdp,
        estado_pdp_excluir=estado_pdp_excluir,
        fecha_compromiso=fecha_compromiso,
        tipo_fono=tipo_fono,
        tipo_fono_excluir=tipo_fono_excluir,
        orden=orden,
        orden_excluir=orden_excluir,
        intentos_equivocado_max=intentos_equivocado_max,
        apagado_ivr_max=apagado_ivr_max,
        fallados_ivr_max=fallados_ivr_max,
        marca_operativa=marca_operativa,
        zona=zona,
        score_min=score_min,
        page=page,
        limit=limit
    )


@router.get("/exportar")
def exportar(
    idcartera: int = Query(...),
    search: str | None = Query(None),
    order_by: str | None = Query("SCORE_FINAL"),
    order_dir: str | None = Query("DESC"),
    condicion: str | None = Query(None),
    nuevo: str | None = Query(None),
    foco: str | None = Query(None),
    prioridad_banco: str | None = Query(None),
    producto: str | None = Query(None),
    rango_mora: str | None = Query(None),
    rango_capital: str | None = Query(None),
    rango_edad: str | None = Query(None),
    empresas_reportantes: str | None = Query(None),
    cuentas: str | None = Query(None),
    anio_cd_historico: str | None = Query(None),
    cluster_ml: str | None = Query(None),
    flag_top: str | None = Query(None),
    rango_campanas: str | None = Query(None),
    caseros: str | None = Query(None),
    estado_civil: str | None = Query(None),
    mg_contacto_cliente: str | None = Query(None),
    mg_indicador_cliente: str | None = Query(None),
    ug_contacto_cliente: str | None = Query(None),
    ug_indicador_cliente: str | None = Query(None),
    estado_pdp: str | None = Query(None),
    origen: str | None = Query(None),
    tipo_base: str | None = Query(None),
    prioridad_fono: str | None = Query(None),
    tipo_fono: str | None = Query(None),
    orden: str | None = Query(None),
    whatsapp: str | None = Query(None),
    osiptel: str | None = Query(None),
    timbrado: str | None = Query(None),
    intentos_equivocados: str | None = Query(None),
    apagados_ivr: str | None = Query(None),
    fallados_ivr: str | None = Query(None),
    zona: str | None = Query(None),
    marca_operativa: str | None = Query(None),
    timbrado_min: int | None = Query(None),
    intentos_equivocado_max: int | None = Query(None),
    apagado_ivr_max: int | None = Query(None),
    fallados_ivr_max: int | None = Query(None),
):
    archivo = exportar_resultados_score(
        idcartera=idcartera,
        search=search,
        order_by=order_by,
        order_dir=order_dir,
        condicion=condicion,
        nuevo=nuevo,
        foco=foco,
        prioridad_banco=prioridad_banco,
        producto=producto,
        rango_mora=rango_mora,
        rango_capital=rango_capital,
        rango_edad=rango_edad,
        empresas_reportantes=empresas_reportantes,
        cuentas=cuentas,
        anio_cd_historico=anio_cd_historico,
        cluster_ml=cluster_ml,
        flag_top=flag_top,
        rango_campanas=rango_campanas,
        caseros=caseros,
        estado_civil=estado_civil,
        mg_contacto_cliente=mg_contacto_cliente,
        mg_indicador_cliente=mg_indicador_cliente,
        ug_contacto_cliente=ug_contacto_cliente,
        ug_indicador_cliente=ug_indicador_cliente,
        estado_pdp=estado_pdp,
        origen=origen,
        tipo_base=tipo_base,
        prioridad_fono=prioridad_fono,
        tipo_fono=tipo_fono,
        orden=orden,
        whatsapp=whatsapp,
        osiptel=osiptel,
        timbrado=timbrado,
        intentos_equivocados=intentos_equivocados,
        apagados_ivr=apagados_ivr,
        fallados_ivr=fallados_ivr,
        zona=zona,
        marca_operativa=marca_operativa,
        timbrado_min=timbrado_min,
        intentos_equivocado_max=intentos_equivocado_max,
        apagado_ivr_max=apagado_ivr_max,
        fallados_ivr_max=fallados_ivr_max,
    )

    return StreamingResponse(
        archivo["stream"],
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={
            "Content-Disposition": f'attachment; filename="{archivo["filename"]}"'
        }
    )


@router.get("/cliente")
def cliente(
    cartera: str = Query(...),
    dni: str = Query(...)
):
    return obtener_telefonos_cliente(cartera=cartera, dni=dni)


@router.get("/catalogos")
def catalogos(
    idcartera: int | None = Query(None)
):
    return obtener_catalogos_score(idcartera=idcartera)


@router.post("/refrescar")
def refrescar():
    return refrescar_score_telefonico()
